const { Telegraf, Markup } = require('telegraf');
const axios = require('axios');
const http = require('http');
require('dotenv').config();

const bot = new Telegraf(process.env.BOT_TOKEN);
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

// Raganork Plugin Maker Guide
const RAGANORK_GUIDE = `Expert Raganork-MD Developer. Return ONLY javascript code. Structure: const { Module } = require('../main'); ... Module({pattern...}). Always use message.sendReply.`;

async function createGist(content) {
    try {
        const response = await axios.post('https://api.github.com/gists', {
            description: "Raganork Plugin Generated by Gemini",
            public: true,
            files: { 'plugin.js': { content: content } }
        }, {
            headers: { Authorization: `token ${GITHUB_TOKEN}` }
        });
        return response.data.html_url;
    } catch (e) {
        return null;
    }
}

bot.on('text', async (ctx) => {
    const userInput = ctx.message.text;
    if (userInput.startsWith('/')) return;

    const waitMsg = await ctx.reply('🔍 _Requesting Gemini via External API..._');

    try {
        // നിങ്ങൾ തന്ന ലിങ്ക് ഉപയോഗിച്ചുള്ള റിക്വസ്റ്റ്
        const apiUrl = `https://gemin-api-weld.vercel.app/api/generateContent?q=${encodeURIComponent(RAGANORK_GUIDE + "\n\nUser: " + userInput)}`;
        
        const response = await axios.get(apiUrl);
        
        // Response ഫോർമാറ്റ് അനുസരിച്ച് ഡാറ്റ എടുക്കുന്നു
        const aiText = response.data.response;

        // കോഡ് മാത്രം വേർതിരിച്ചെടുക്കുന്നു
        const codeMatch = aiText.match(/```javascript([\s\S]*?)```/) || aiText.match(/```([\s\S]*?)```/);
        const pluginCode = codeMatch ? codeMatch[1].trim() : (aiText.includes('Module') ? aiText.trim() : null);

        if (pluginCode) {
            const link = await createGist(pluginCode);
            if (link) {
                await ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, null, 
                    `✅ *Plugin Generated!*\n\n🔗 *Link:* ${link}`, 
                    { 
                        parse_mode: 'Markdown', 
                        ...Markup.inlineKeyboard([Markup.button.url('📂 View Code', link)]) 
                    }
                );
            } else {
                await ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, null, "❌ Gist Creation Failed. Check GITHUB_TOKEN.");
            }
        } else {
            // കോഡ് അല്ലെങ്കിൽ നോർമൽ ടെക്സ്റ്റ് ആയി മറുപടി നൽകുന്നു
            await ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, null, aiText);
        }
    } catch (error) {
        await ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, null, "❌ External API is down or not responding.");
    }
});

// Render-ൽ ബോട്ട് ഓഫ് ആകാതിരിക്കാൻ
http.createServer((req, res) => { res.write('Gemini Bot Running'); res.end(); }).listen(process.env.PORT || 8080);

bot.launch();
console.log("Bot is Online!");
